project:
  type: website

website:
  title: "Simon Says"
  site-url: https://simonguest.com
  description: "The blog of Simon Guest"
  navbar:
    right:
      - about/index.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/simonguest/
      - icon: github
        href: https://github.com/simonguest
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header: analytics.html
